INSERT INTO lecture (title, teacher_name, capacity, lecture_date) VALUES ('자바', '이경록1', 30, NOW());
INSERT INTO lecture (title, teacher_name, capacity, lecture_date) VALUES ('파이썬', '이경록2', 20, NOW());
INSERT INTO lecture (title, teacher_name, capacity, lecture_date) VALUES ('C언어', '이경록3', 30, NOW());

INSERT INTO user_info (user_id, password) VALUES ('user1', '1234');
INSERT INTO user_info (user_id, password) VALUES ('user2', '1234');
INSERT INTO user_info (user_id, password) VALUES ('user3', '1234');
INSERT INTO user_info (user_id, password) VALUES ('user4', '1234');
INSERT INTO user_info (user_id, password) VALUES ('user5', '1234');
INSERT INTO user_info (user_id, password) VALUES ('user6', '1234');
INSERT INTO user_info (user_id, password) VALUES ('user7', '1234');
INSERT INTO user_info (user_id, password) VALUES ('user8', '1234');
INSERT INTO user_info (user_id, password) VALUES ('user9', '1234');
INSERT INTO user_info (user_id, password) VALUES ('user10', '1234');
INSERT INTO user_info (user_id, password) VALUES ('user11', '1234');
INSERT INTO user_info (user_id, password) VALUES ('user12', '1234');
INSERT INTO user_info (user_id, password) VALUES ('user13', '1234');
INSERT INTO user_info (user_id, password) VALUES ('user14', '1234');
INSERT INTO user_info (user_id, password) VALUES ('user15', '1234');
INSERT INTO user_info (user_id, password) VALUES ('user16', '1234');
INSERT INTO user_info (user_id, password) VALUES ('user17', '1234');
INSERT INTO user_info (user_id, password) VALUES ('user18', '1234');
INSERT INTO user_info (user_id, password) VALUES ('user19', '1234');
INSERT INTO user_info (user_id, password) VALUES ('user20', '1234');
INSERT INTO user_info (user_id, password) VALUES ('user21', '1234');
INSERT INTO user_info (user_id, password) VALUES ('user22', '1234');
INSERT INTO user_info (user_id, password) VALUES ('user23', '1234');
INSERT INTO user_info (user_id, password) VALUES ('user24', '1234');
INSERT INTO user_info (user_id, password) VALUES ('user25', '1234');
INSERT INTO user_info (user_id, password) VALUES ('user26', '1234');
INSERT INTO user_info (user_id, password) VALUES ('user27', '1234');
INSERT INTO user_info (user_id, password) VALUES ('user28', '1234');
INSERT INTO user_info (user_id, password) VALUES ('user29', '1234');
INSERT INTO user_info (user_id, password) VALUES ('user30', '1234');
INSERT INTO user_info (user_id, password) VALUES ('user31', '1234');
INSERT INTO user_info (user_id, password) VALUES ('user32', '1234');
INSERT INTO user_info (user_id, password) VALUES ('user33', '1234');
INSERT INTO user_info (user_id, password) VALUES ('user34', '1234');
INSERT INTO user_info (user_id, password) VALUES ('user35', '1234');
INSERT INTO user_info (user_id, password) VALUES ('user36', '1234');
INSERT INTO user_info (user_id, password) VALUES ('user37', '1234');
INSERT INTO user_info (user_id, password) VALUES ('user38', '1234');
INSERT INTO user_info (user_id, password) VALUES ('user39', '1234');
INSERT INTO user_info (user_id, password) VALUES ('user40', '1234');